config/routes.rb
Rails.application.routes.draw do  
  resources :preferencias
  resources :preferencia
  resources :turmas
  resources :niveis
  resources :disciplinas
  resources :areas_formacoes
  resources :turnos
  devise_for :users, skip: [:registrations], path: "auth"
  resources :users, path: "usuarios"
  root "home#index"
end

app/views/shared/sidebar/_sidebar.html.erb
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-xl" style="background-color: #01411C">
  <!-- Sidebar content -->
  <div class="sidebar-content">
    <!-- Sidebar header -->
    <div class="sidebar-section">
      <div class="sidebar-section-body d-flex justify-content-center">
        <h5 class="sidebar-resize-hide flex-grow-1 my-auto">Menu</h5>
        <div>
          <button type="button" class="btn btn-flat-white btn-icon btn-sm rounded-pill border-transparent sidebar-mobile-main-toggle d-xl-none">
            <i class="ph-x"></i>
          </button>
        </div>
      </div>
    </div>
    <!-- /sidebar header -->
    <!-- Main navigation -->
    <div class="sidebar-section">
      <ul class="nav nav-sidebar" data-nav-type="accordion">
        <!-- Main -->
        <%= link_to users_path, class: "nav-link #{" active" if params[:controller] == "users" }" do %>
          <i class="ph-users-three"></i>
          <%=  t("activerecord.models.#{User.model_name.i18n_key}.other") %>
        <% end %>
        <%= link_to preferencias_path, class: "nav-link #{" active" if params[:controller] == "preferencias" }" do %>
          <i class="ph-chat-dots"></i>
          <%=  t("activerecord.models.#{Preferencia.model_name.i18n_key}.other") %>
        <% end %>
        <li class="nav-item-header">
          <div class="text-uppercase fs-sm lh-sm opacity-50 sidebar-resize-hide">-----------------------------------------------</div>
        </li>
        <%= link_to areas_formacoes_path, class: "nav-link #{" active" if params[:controller] == "areas_formacoes" }" do %>
          <i class="ph-briefcase"></i>
          <%=  t("activerecord.models.#{AreaFormacao.model_name.i18n_key}.other") %>
        <% end %>
        <%= link_to disciplinas_path, class: "nav-link #{" active" if params[:controller] == "disciplinas" }" do %>
          <i class="ph-books"></i>
          <%=  t("activerecord.models.#{Disciplina.model_name.i18n_key}.other") %>
        <% end %>
        <%= link_to niveis_path, class: "nav-link #{" active" if params[:controller] == "niveis" }" do %>
          <i class="ph-graduation-cap"></i>
          <%=  t("activerecord.models.#{Nivel.model_name.i18n_key}.other") %>
        <% end %>
        <%= link_to turmas_path, class: "nav-link #{" active" if params[:controller] == "turmas" }" do %>
          <i class="ph-chalkboard-simple"></i>
          <%=  t("activerecord.models.#{Turma.model_name.i18n_key}.other") %>
        <% end %>
        <%= link_to turnos_path, class: "nav-link #{" active" if params[:controller] == "turnos" }" do %>
          <i class="ph-clock"></i>
          <%=  t("activerecord.models.#{Turno.model_name.i18n_key}.other") %>
        <% end %>
      </ul>
    </div>
    <!-- /main navigation -->
  </div>
  <!-- /sidebar content -->
</div>