config/routes.rb
Rails.application.routes.draw do  
  resources :preferencias
  resources :preferencia
  resources :turmas
  resources :niveis
  resources :disciplinas
  resources :areas_formacoes
  resources :turnos
  devise_for :users, skip: [:registrations], path: "auth"
  resources :users, path: "usuarios"
  root "home#index"
end

app/models/preferencia.rb
class Preferencia < ApplicationRecord
  belongs_to :turno
  belongs_to :disciplina
  belongs_to :user
end

app/controllers/preferencias_controller.rb
class PreferenciasController < ApplicationController
  before_action :set_preferencia, only: %i[ edit update destroy ]

  def index
    @q = Preferencia.ransack(params[:q])
    @pagy, @preferencias = pagy(@q.result)
  end

  def new
    @preferencia = Preferencia.new
  end

  def edit
  end

  def create
    @preferencia = Preferencia.new(preferencia_params.merge(user: current_user))

    if @preferencia.save
      redirect_to preferencias_path, notice: "Registro cadastrado com sucesso!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @preferencia.update(preferencia_params)
      redirect_to preferencias_path, notice: "Registro atualizado com sucesso!", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @preferencia.soft_delete
      redirect_to preferencias_url, notice: "Registro foi marcado como excluído."
    else
      redirect_to preferencias_url, alert: "Ainda existem dependentes desse registro."
    end   
  end

  private

  def set_preferencia
    @preferencia = Preferencia.find(params[:id])
  end

  def preferencia_params
    params.require(:preferencia).permit(Preferencia.column_names.reject { |col| ['deleted_at', 'created_by', 'updated_by'].include?(col) }.map(&:to_sym))    
  end
end

app/views/preferencias/_form.html.erb
<%= render "shared/context_nav", title: t("activerecord.models.#{Preferencia.model_name.i18n_key}.other") do  %>
  <span class="breadcrumb-item"><%= link_to t("activerecord.models.#{Preferencia.model_name.i18n_key}.other"), preferencias_path, class: "text-dark" %></span>
  <span class="breadcrumb-item active"><%= t("helpers.submit.#{params[:action]}") %></span>
<% end %>
<%= simple_form_for(@preferencia) do |f| %>
  <div class="card">
    <div class="card-header">
      <h5 class="my-0">
        <%= @preferencia.new_record? ? "Incluir " : "Editar " %><%= t("activerecord.models.#{Preferencia.model_name.i18n_key}.one") %>
      </h5>
    </div>
    <div class="card-body">
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= render "shared/notice" %>
      <div class="row">
        <div class="col-12 col-lg-6">
          <%= f.association :turno, input_html: { class: "keyup select2"}  %>
        </div>
        <div class="col-12 col-lg-6">
          <%= f.association :disciplina, input_html: { class: "keyup select2"}  %>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <%= btn_submit(f) %>
      <%= link_to "Voltar", preferencias_path, class: "btn btn-light" %>
    </div>
  </div>
<% end %>

app/views/preferencias/_preferencia.html.erb
<div id="<%= dom_id preferencia %>">
  <p>
    <strong>Turno:</strong>
    <%= preferencia.turno_id %>
  </p>

  <p>
    <strong>Disciplina:</strong>
    <%= preferencia.disciplina_id %>
  </p>

</div>

app/views/preferencias/edit.html.erb
<%= render "form" %>

app/views/preferencias/index.html.erb
<%= render "shared/context_nav", title: t("activerecord.models.#{Preferencia.model_name.i18n_key}.other"), new_path: new_preferencia_path do  %>
  <span class="breadcrumb-item active"><%= t("activerecord.models.#{Preferencia.model_name.i18n_key}.other") %></span>
<% end %>
<div class="card">
  <div class="card-header d-flex">
    <%= search_form_for @q, html: { class: "d-flex gap-2" , autocomplete: "off"} do |f| %>
      <%= f.search_field :turno_descricao_cont, class: "form-control", placeholder: t("activerecord.attributes.preferencia.turno") %>
      <%= f.button(type: 'submit', class: 'btn btn-info') { tag.i(class: 'ph-magnifying-glass') } %>
      <%= link_to  tag.i(class: 'ph-x-circle'), preferencias_path, class: "btn btn-light" if params[:q] %>
    <% end %>
  </div>
  <div class="card-body">
    <%= render "shared/notice" %>
    <div class= "table-responsive">
      <table class="table table-sm table-bordered table-striped">
        <thead>
          <tr>
            <th><%= sort_link(@q, :turno, t("activerecord.attributes.preferencia.turno")) %></th>
            <th><%= sort_link(@q, :disciplina, t("activerecord.attributes.preferencia.disciplina")) %></th>
            <th class="text-center">Ações</th>
          </tr>
        </thead>
        <tbody>
          <% @preferencias.each do |preferencia| %>
            <tr>
              <td><%= preferencia.turno %></td>
              <td><%= preferencia.disciplina %></td>
              <td class="text-center">
                <div class="dropdown-toggle">
                  <a href="#" class="text-body dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="ph-gear"></i>
                  </a>
                  <div class="dropdown-menu" style="">
                    <div class="dropdown-header">Opções</div>
                    <%= link_to edit_preferencia_path(preferencia), class: "dropdown-item" do %>
                      <i class="ph-pen me-2"></i> Editar
                    <% end %>
                    <%= form_for preferencia, method: :delete do |f| %>
                      <a class="dropdown-item hand-pointer " data-confirm-delete="<%= preferencia_path(preferencia) %>" data-csrf-token="<%= form_authenticity_token %>">
                        <i class="ph-trash-simple me-2"></i>Excluir
                      </a>
                    <% end %>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="card-footer">
    <%= render "shared/pagy", pagy: @pagy %>
  </div>
</div>

app/views/preferencias/new.html.erb
<%= render "form" %>

app/views/preferencias/show.html.erb
<div class="container">
  <%= render "shared/notice" %>
  <div class="card border-0 shadow shadow-sm">
    <div class="card-header border-0 d-flex justify-content-between">
      <span class="fs-4">Visualizar Preferencia</span>
    </div>
    <div class="card-body">
      <div id="<%= dom_id @preferencia %>">
              
          <p>
            <strong>Turno:</strong>
            <%= @preferencia.turno %>
          </p>
              
          <p>
            <strong>Disciplina:</strong>
            <%= @preferencia.disciplina %>
          </p>
     
      </div>
    </div>
    <div class="card-footer border-0 d-flex justify-content-between">
      <div>
        <%= link_to edit_preferencia_path(@preferencia), class: "btn btn-primary" do %>
          <i class="bi bi-pencil-square"></i> Editar
        <% end %>
        <%= link_to "Voltar", preferencias_path, class: "btn btn-secondary" %>
      </div>
      <%= button_to "Deletar", @preferencia, method: :delete, class: "btn btn-outline-danger border-0" %>
    </div>
  </div>
</div>