config/routes.rb
Rails.application.routes.draw do  
  resources :preferencias
  resources :preferencia
  resources :turmas
  resources :niveis
  resources :disciplinas
  resources :areas_formacoes
  resources :turnos
  devise_for :users, skip: [:registrations], path: "auth"
  resources :users, path: "usuarios"
  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, authentication_keys: [:cpf]
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, authentication_keys: [:cpf]
  
  
  validates :cpf, presence: true, uniqueness: true
  validates :nome, presence: true, uniqueness: true
  validates :email, presence: true
  validate :custom_validates
  
  has_many :preferencias
  
  def nome=(nome)
    super nome = nome.upcase
  end

  def cpf=(cpf)
    super cpf = cpf.gsub(/[.-]/, "")
  end
  
  def custom_validates
    # Validação de CPF
    unless CPF.valid?(cpf)
      errors.add(:cpf, "não é válido")
    end          
  end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]
  before_action :verify_admin, only: %i[index new create destroy]
  before_action :verify_access, only: %i[edit update]

  def index
    @q = User.ransack(params[:q])
    @pagy, @users = pagy(@q.result)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params.merge(created_by: current_user.cpf))
    if @user.save
      redirect_to users_path, notice: "Registro cadastrado com sucesso!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "Registro atualizado com sucesso!", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.soft_delete
      redirect_to users_path, notice: "Registro foi marcado como excluído."
    else
      redirect_to users_path, alert: "Ainda existem dependentes desse registro."
    end
  end

  private

  def verify_admin
    redirect_to(root_path, alert: "Seu perfil não possui acesso.") unless current_user.admin?
  end

  def verify_access
    return if current_user.admin? || current_user == @user
    redirect_to root_path, alert: "Seu perfil não possui acesso."
  end

  def set_user
    @user = User.find_by_id(params[:id])
    redirect_to(root_path, alert: "Seu perfil não possui acesso.") unless @user
    @user.updated_by = current_user.cpf
  end

  def user_params
    params.require(:user).permit(
      :email,
      :cpf,
      :admin,
      :nome,
      :password,
      :password_confirmation
    )
  end
end

app/views/users/_form.html.erb
<%= render "shared/context_nav", title: t("activerecord.models.#{User.model_name.i18n_key}.other") do  %>
  <span class="breadcrumb-item"><%= link_to t("activerecord.models.#{User.model_name.i18n_key}.other"), users_path, class: "text-dark" %></span>
  <span class="breadcrumb-item active"><%=  t("helpers.submit.#{params[:action]}") %></span>
<% end %>
<%= simple_form_for(@user) do |f| %>
  <div class="card">
    <div class="card-header">
      <h5 class="mb-0">
        <%= @user.new_record? ? "Incluir " : "Editar " %><%= t("activerecord.models.#{User.model_name.i18n_key}.one") %>
      </h5>
    </div>
    <div class="card-body">
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= render "shared/notice" %>
      <div class="row">
        <div class="col-12 col-xl-4 col-lg-3 col-md-4">
          <%= f.input :cpf, input_html: { class: "keyup cpf"}  %>
        </div>
        <div class="col-12 col-xl-4 col-lg-4 col-md-8">
          <%= f.input :nome, input_html: { class: "keyup"}  %>
        </div>
        <div class="col-12 col-xl-4 col-lg-5">
          <%= f.input :email, input_html: { class: "downcase"}  %>
        </div>
        <div class="col-12">
          <%= f.input :admin, input_html: { class: "keyup"}  %>
        </div>
        <div class="col-12 col-lg-6">
          <%= f.input :password %>
        </div>
        <div class="col-12 col-lg-6">
          <%= f.input :password_confirmation %>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <%= btn_submit(f) %>
      <buttom class="btn btn-light" onclick="window.history.back();">Voltar</buttom>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/index.html.erb
<%= render "shared/context_nav", title: t("activerecord.models.#{User.model_name.i18n_key}.other"), new_path: new_user_path do  %>
  <span class="breadcrumb-item active"><%= t("activerecord.models.#{User.model_name.i18n_key}.other") %></span>
<% end %>
<div class="card">
  <div class="card-header d-flex">
    <%= search_form_for @q, html: { class: "d-flex gap-2" , autocomplete: "off"} do |f| %>
      <%= 
        f.search_field :nome_or_cpf_or_email_cont, 
        class: "form-control", 
        placeholder: "Pesquisar",
        "data-bs-popup": "tooltip",
		    "data-bs-original-title": "Pesquise por Nome, Email ou CPF sem .-"
      %>
      <%= f.button(type: 'submit', class: 'btn btn-info') { tag.i(class: 'ph-magnifying-glass') } %>
      <%= link_to tag.i(class: "ph-x-circle"), users_path, class: "btn btn-light" if params[:q]%>
    <% end %>
  </div>
  <div class="card-body">
    <%= render "shared/notice" %>
    <table class="table table-sm table-bordered table-striped">
      <thead>
        <tr>
          <th><%= sort_link(@q, :cpf,  t("activerecord.attributes.user.cpf")) %></th>
          <th><%= sort_link(@q, :nome,  t("activerecord.attributes.user.nome")) %></th>
          <th><%= sort_link(@q, :email, t("activerecord.attributes.user.email")) %></th>
          <th class="text-center">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= formatar_cpf(user.cpf) %></td>
            <td><%= user.nome %></td>
            <td><%= user.email %></td>
            <td class="text-center">
              <div class="dropdown">
                <a href="#" class="text-body dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="ph-gear"></i>
                </a>
                <div class="dropdown-menu" style="">
                  <div class="dropdown-header">Opções</div>
                  <%= link_to edit_user_path(user), class: "dropdown-item" do %>
                    <i class="ph-pen me-2"></i> Editar
                  <% end %>
                  <%= form_for user, method: :delete do |f| %>
                    <a class="dropdown-item hand-pointer " data-confirm-delete="<%= user_path(user) %>" data-csrf-token="<%= form_authenticity_token %>">
                      <i class="ph-trash-simple me-2"></i>Excluir
                    </a>
                  <% end %>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <%= render "shared/pagy", pagy: @pagy %>
  </div>
</div>

app/views/users/new.html.erb
<%= render "form" %>