config/routes.rb
Rails.application.routes.draw do  
  resources :preferencias
  resources :preferencia
  resources :turmas
  resources :niveis
  resources :disciplinas
  resources :areas_formacoes
  resources :turnos
  devise_for :users, skip: [:registrations], path: "auth"
  resources :users, path: "usuarios"
  root "home#index"
end

app/models/turno.rb
class Turno < ApplicationRecord
  has_many :turmas
  has_many :preferencias

  validates :descricao, presence: true, uniqueness: true

  def descricao=(descricao)
    super descricao.upcase.strip
  end

  def to_s
    descricao
  end
end

app/controllers/turnos_controller.rb
class TurnosController < ApplicationController
  before_action :set_turno, only: %i[ edit update destroy ]

  def index
    @q = Turno.ransack(params[:q])
    @pagy, @turnos = pagy(@q.result)
  end

  def new
    @turno = Turno.new
  end

  def edit
  end

  def create
    @turno = Turno.new(turno_params)

    if @turno.save
      redirect_to turnos_path, notice: "Registro cadastrado com sucesso!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @turno.update(turno_params)
      redirect_to turnos_path, notice: "Registro atualizado com sucesso!", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @turno.soft_delete
      redirect_to turnos_url, notice: "Registro foi marcado como excluído."
    else
      redirect_to turnos_url, alert: "Ainda existem dependentes desse registro."
    end   
  end

  private

  def set_turno
    @turno = Turno.find(params[:id])
  end

  def turno_params
    params.require(:turno).permit(Turno.column_names.reject { |col| ['deleted_at', 'created_by', 'updated_by'].include?(col) }.map(&:to_sym))    
  end
end

app/views/turnos/_form.html.erb
<%= render "shared/context_nav", title: t("activerecord.models.#{Turno.model_name.i18n_key}.other") do  %>
  <span class="breadcrumb-item"><%= link_to t("activerecord.models.#{Turno.model_name.i18n_key}.other"), turnos_path, class: "text-dark" %></span>
  <span class="breadcrumb-item active"><%= t("helpers.submit.#{params[:action]}") %></span>
<% end %>

<%= simple_form_for(@turno) do |f| %>
  <div class="card">
    <div class="card-header">
      <h5 class="my-0">
        <%= @turno.new_record? ? "Incluir " : "Editar " %><%= t("activerecord.models.#{Turno.model_name.i18n_key}.one") %>
      </h5>
    </div>    
    <div class="card-body">
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>    
      <%= render "shared/notice" %>  
      <div class="row">
        
          
            <div class="col-12">
              <%= f.input :descricao, input_html: { class: "keyup "}  %>
            </div>
          
      </div>
    </div>
    <div class="card-footer">
      <%= btn_submit(f) %>
      <%= link_to "Voltar", turnos_path, class: "btn btn-light" %>
    </div>
  </div>
<% end %>

app/views/turnos/_turno.html.erb
<div id="<%= dom_id turno %>">
  <p>
    <strong>Descricao:</strong>
    <%= turno.descricao %>
  </p>

</div>

app/views/turnos/edit.html.erb
<%= render "form" %>

app/views/turnos/index.html.erb
<%= render "shared/context_nav", title: t("activerecord.models.#{Turno.model_name.i18n_key}.other"), new_path: new_turno_path do  %>
  <span class="breadcrumb-item active"><%= t("activerecord.models.#{Turno.model_name.i18n_key}.other") %></span>
<% end %>
<div class="card">
  <div class="card-header d-flex">
    <%= search_form_for @q, html: { class: "d-flex gap-2" , autocomplete: "off"} do |f| %>
      <%= f.search_field :descricao_cont, class: "form-control", placeholder: t("activerecord.attributes.turno.descricao") %>
      <%= f.button(type: 'submit', class: 'btn btn-info') { tag.i(class: 'ph-magnifying-glass') } %>
      <%= link_to  tag.i(class: 'ph-x-circle'), turnos_path, class: "btn btn-light" if params[:q] %>
    <% end %>
  </div>
  <div class="card-body">
    <%= render "shared/notice" %>
    <div class= "table-responsive">
      <table class="table table-sm table-bordered table-striped">
        <thead>
          <tr>
            <th><%= sort_link(@q, :descricao, t("activerecord.attributes.turno.descricao")) %></th>
            <th class="text-center">Ações</th>
          </tr>
        </thead>
        <tbody>
          <% @turnos.each do |turno| %>
            <tr>
              <td><%= turno.descricao %></td>
              <td class="text-center">
                <div class="dropdown-toggle">
                  <a href="#" class="text-body dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="ph-gear"></i>
                  </a>
                  <div class="dropdown-menu" style="">
                    <div class="dropdown-header">Opções</div>
                    <%= link_to edit_turno_path(turno), class: "dropdown-item" do %>
                      <i class="ph-pen me-2"></i> Editar
                    <% end %>
                    <%= form_for turno, method: :delete do |f| %>
                      <a class="dropdown-item hand-pointer " data-confirm-delete="<%= turno_path(turno) %>" data-csrf-token="<%= form_authenticity_token %>">
                        <i class="ph-trash-simple me-2"></i>Excluir
                      </a>
                    <% end %>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="card-footer">
    <%= render "shared/pagy", pagy: @pagy %>
  </div>
</div>

app/views/turnos/new.html.erb
<%= render "form" %>

app/views/turnos/show.html.erb
<div class="container">
  <%= render "shared/notice" %>
  <div class="card border-0 shadow shadow-sm">
    <div class="card-header border-0 d-flex justify-content-between">
      <span class="fs-4">Visualizar Turno</span>
    </div>
    <div class="card-body">
      <div id="<%= dom_id @turno %>">
        <p>
          <strong>Descricao:</strong>
          <%= @turno.descricao %>
        </p>
      </div>
    </div>
    <div class="card-footer border-0 d-flex justify-content-between">
      <div>
        <%= link_to edit_turno_path(@turno), class: "btn btn-primary" do %>
          <i class="bi bi-pencil-square"></i> Editar
        <% end %>
        <%= link_to "Voltar", turnos_path, class: "btn btn-secondary" %>
      </div>
      <%= button_to "Deletar", @turno, method: :delete, class: "btn btn-outline-danger border-0" %>
    </div>
  </div>
</div>